--- 
- 
  apt: update_cache=yes
  name: "Update apt caches"
- 
  apt: 
    upgrade: dist
  name: "Upgrade apt packages"
- 
  apt: "name={{item}} update_cache=true state=latest"
  name: "Install dev apt packages"
  with_items: 
    - git
    - ruby-dev
    - xauth
