language: node_js

node_js:
   - "node"

before_script:
   - npm install -g gulp

script: gulp

notifications:
  slack:
    secure: EiIRnkgjv2Rbn1fhlljkaRQJaA2w+RhO9531AWYIHki3iZIXYR8OSe2iItPOlatL18gl4/zT6ey+PrGEcTCTcnbuZxoj1n9Adf3/Gm1lleXAjNFSL+bVx7v+WxRKgVS+82yrA5TmxMBZnZy+cCp3YGSWZf3RBD1pMrq1uuSIcIC5etc/V0nnBtYZPv91wKG9RiTL4gXxzB7Y7EYrJ4oDYj0AD5U4V18FwtY3+Hs/02/8QqsDLmP8tDHFsCso+9N483y7hNhxd57v7GeSm8DEFWDTq1Q7OuLv73l8kV1b4D7YGFcFiOKnoDhFVGCJ98Gzhcc3KIHt4ULGZPept4kQSKLSz9oVZmFMpBwamPlHY1bejQh4scWmz/XzcWBFUUWdxrNvld024/ClcL9rdtdscL5I9WZ37/w4Pi0s76NgrU1mvXFoHi1ADzwMGOsaRZhalcPjl4MalghjyiTo60KsOT1H9xqLx6Ni2Drdk9Z+zs32rMcNi2LQJpWslFe0sua30GQrnw03P3clg0WvJ+O+VZwz4HAIgGj0hv5HXyJ4X3JfPdoJ+zf8qn9sFMrBVg1DCe4Ffl8EfCTtLQclhErcDzXrL3BwaOcVyAvblFI/f4aoZ+hVHIqhjUyOZPRPwAA9UTxdRSLwg/1wQh8GB9txiOXk2dqZ2CC8GNAnL07HK4I=
